### ISSUE TITLE
我下载了mac版，但是不知道用啥打开，格式是.dms

### ISSUE THREAD

**Issue by Bearxxuan** [airob0t/idcardgenerator#16]
有没有类似dmg格式的安装包呀，感谢

**Comment by airob0t** [comment]
是可执行程序，直接运行，pip安装应该也没问题

**Comment by Bearxxuan** [comment]
我用chrome下载Mac版，是没有后缀的呀。我把后缀改成.app .zip .dmg .rar都打不开那个文件，看来只能用pip安装了吧
