### ISSUE TITLE
不支持透明背景的图

### ISSUE THREAD

**Issue by ssyangchn** [airob0t/idcardgenerator#7]
透明背景的PNG，选择不自动抠图，出来的照片还是有白色或黑色背景

**Comment by airob0t** [comment]
白色或黑色？怎么会有两种情况
请提供详细运行环境信息

**Comment by eromoe** [comment]
原图
![1505290997_45734](https://user-images.githubusercontent.com/3938751/50832900-8f2cc000-138a-11e9-82d3-05bc5ca3efb0.jpg)

用抠图转出来的png
![-20190108-211350](https://user-images.githubusercontent.com/3938751/50832844-6b697a00-138a-11e9-8d96-35e3afff36bd.png)


结果
![image](https://user-images.githubusercontent.com/3938751/50832885-850ac180-138a-11e9-86c2-21f8e4cb1775.png)

**Comment by airob0t** [comment]
已修复
